from numba import njit, prange
import numpy as np
from wise_scattering.physics_utilities import flat_to_matrix_coords

@njit(cache=True)
def construct_coupling_matrix_jit(r_val, prefactor, n_channels,
                                  pot_flat_pos, pot_terms_per_elem, pot_lambda_idx, pot_coeffs, 
                                  radial_pot_row,
                                  cent_flat_pos, cent_coeffs):
    """
    Constructs the total coupling matrix V(r) at a specific radial grid point.
    
    This evaluates the scaled interaction potential matrix:
    V_ij = -2μ * V_pot(r) - l(l+1)/r^2
    
    Parameters
    ----------
    r_val : float
        The current radial grid point.
    prefactor : float
        The reduced mass prefactor (2μ).
    n_channels : int
        The total number of channels in the basis set.
    pot_flat_pos, pot_terms_per_elem, pot_lambda_idx, pot_coeffs : np.ndarray
        Sparse mapping arrays for the potential matrix generated by `precompute_potential_sparsity`.
    radial_pot_row : np.ndarray
        A 1D array representing the interpolated radial potential evaluated at `r_val`.
    cent_flat_pos, cent_coeffs : np.ndarray
        Sparse mapping arrays for the centrifugal matrix.

    Returns
    -------
    np.ndarray
        A 2D dense float64 matrix representing the coupling evaluated at r.
    """
    # Allocate as float64, just like the original functions
    V = np.zeros((n_channels, n_channels), dtype=np.float64)
    
    # --- 1. Potential Contribution ---
    innermost_index = 0
    for idx in range(len(pot_flat_pos)):
        position = pot_flat_pos[idx]
        i, j = flat_to_matrix_coords(position)
        
        value = 0.0
        n_terms = pot_terms_per_elem[idx]
        for n_lambda in range(n_terms):
            value += pot_coeffs[innermost_index] * radial_pot_row[pot_lambda_idx[innermost_index]]
            innermost_index += 1
            
        # Apply the -prefactor exactly as the original formulation
        scaled_value = -prefactor * value
        V[i, j] = scaled_value
        V[j, i] = scaled_value

    # --- 2. Centrifugal Contribution ---
    for idx in range(len(cent_flat_pos)):
        position = cent_flat_pos[idx]
        i, j = flat_to_matrix_coords(position)
        
        # Apply the -1/r^2 scaling exactly as the original formulation
        cent_val = -cent_coeffs[idx] / (r_val**2)
        
        # Add to existing potential (don't overwrite!)
        V[i, j] += cent_val
        if i != j:
            V[j, i] += cent_val
        
    return V

@njit(fastmath=True, parallel=True)
def compute_U_psi_jit(psi_phys, grid, prefactor, pot_data, radial_pot, cent_data):
    """
    Computes the action of the physical potential operator U on the full wavefunction.
    
    Used for computing S-matrix elements via Eq. (11) in the manuscript.
    
    Parameters
    ----------
    psi_phys : np.ndarray
        The un-symmetrized physical wavefunction matrix of shape (C, N).
    grid : np.ndarray
        The radial spatial grid.
    prefactor : float
        The mass prefactor (2μ).
    pot_data, cent_data : tuple
        Unpacked tuples containing the sparse potential and centrifugal mappings.
    radial_pot : np.ndarray
        The fully interpolated dense 2D radial potential matrix.

    Returns
    -------
    np.ndarray
        A 2D complex128 array of shape (C, N) representing the scaled potential action.
    """
    C, N = psi_phys.shape
    U_psi = np.zeros_like(psi_phys)
    for j in prange(N):
        # We use the exact same negative constructor to get U
        V_j = -construct_coupling_matrix_jit(grid[j], prefactor, C, *pot_data, radial_pot[j], *cent_data)
        U_psi[:, j] = V_j.astype(np.complex128) @ psi_phys[:, j]
    return U_psi

@njit(fastmath=True, parallel=True)
def apply_K_matvec(psi_in, grid, sqrt_w, prefactor, G_diag, R_ratio, 
                   pot_data, radial_pot, cent_data):
    """
    Matrix-free evaluator passed to the Arnoldi eigensolver: K|ψ⟩ = G * U * |ψ⟩.

    Parameters
    ----------
    psi_in : np.ndarray
        A flattened 1D array representing the state vector.
    grid : np.ndarray
        The radial spatial grid.
    sqrt_w : np.ndarray
        The square roots of the integration weights (for symmetrization).
    prefactor : float
        The reduced mass prefactor.
    G_diag : np.ndarray
        The diagonal elements of the reference Green's functions.
    R_ratio : np.ndarray
        The regular solution outward Numerov ratios.
    pot_data, cent_data : tuple
        Unpacked tuples containing sparse interaction matrix data.
    radial_pot : np.ndarray
        Dense radial potential matrix.

    Returns
    -------
    np.ndarray
        The resulting flattened 1D array after applying K.
    """
    C, N = G_diag.shape[0], len(grid)
    
    # Symmetrize
    psi_symm = np.empty_like(psi_in)
    for i in prange(N):
        for k in range(C):
            psi_symm[i*C + k] = psi_in[i*C + k] * sqrt_w[i]

    # V @ psi Stage
    V_psi = np.zeros((N, C), dtype=np.complex128)
    for j in prange(N):
        V_j = - construct_coupling_matrix_jit(grid[j], prefactor, C, *pot_data, radial_pot[j], *cent_data)
        V_psi[j, :] = V_j.astype(np.complex128) @ psi_symm[j*C : (j+1)*C]

    # Green's Function Sweep Stage
    psi_out_symm = np.zeros_like(psi_in)
    for c in prange(C):
        # Forward sweep
        prev_L = G_diag[c, 0] * V_psi[0, c]
        psi_out_symm[0*C + c] = prev_L
        for i in range(1, N):
            factor = (G_diag[c, i] / G_diag[c, i-1]) * R_ratio[c, i]
            curr_L = factor * prev_L + G_diag[c, i] * V_psi[i, c]
            psi_out_symm[i*C + c] = curr_L
            prev_L = curr_L
        # Backward sweep
        prev_U = 0.0j
        for i in range(N-2, -1, -1):
            curr_U = R_ratio[c, i+1] * (G_diag[c, i+1] * V_psi[i+1, c] + prev_U)
            psi_out_symm[i*C + c] += curr_U
            prev_U = curr_U

    # De-symmetrize
    psi_out = np.empty_like(psi_in)
    for i in prange(N):
        for k in range(C):
            psi_out[i*C + k] = psi_out_symm[i*C + k] * sqrt_w[i]
    return psi_out

@njit(fastmath=True, parallel=True)
def apply_KH_matvec(psi_in, grid, sqrt_w, prefactor, G_diag, R_ratio, 
                    pot_data, radial_pot, cent_data):
    """
    Computes the adjoint operator K^H |ψ⟩ = U^H * G^H * |ψ⟩.

    Required by the Arnoldi eigensolver for left-eigenspace calculations to identify biorthogonal 
    eigenvectors of the non-Hermitian operator K.

    Parameters
    ----------
    (Matches apply_K_matvec exactly)

    Returns
    -------
    np.ndarray
        The resulting flattened 1D array after applying K^H.
    """
    C, N = G_diag.shape[0], len(grid)

    # Symmetrize input
    psi_symm = np.empty_like(psi_in)
    for i in prange(N):
        for k in range(C):
            psi_symm[i*C + k] = psi_in[i*C + k] * sqrt_w[i]

    G_psi_H = np.zeros_like(psi_in)

    # --- STAGE 1: Green's Function Sweeps (Apply G^H) ---
    for c in prange(C):
        G_diag_conj = np.conj(G_diag[c, :])
        R_ratio_conj = np.conj(R_ratio[c, :])
        
        # Forward Sweep
        prev_S = G_diag_conj[0] * psi_symm[0*C + c]
        G_psi_H[0*C + c] = prev_S
        for i in range(1, N):
            factor = (G_diag_conj[i] / G_diag_conj[i-1]) * R_ratio_conj[i]
            current_S = factor * prev_S + G_diag_conj[i] * psi_symm[i*C + c]
            G_psi_H[i*C + c] = current_S
            prev_S = current_S

        # Backward Sweep
        prev_U = 0.0j
        for i in range(N-2, -1, -1):
            current_U = R_ratio_conj[i+1] * (G_diag_conj[i+1] * psi_symm[(i+1)*C + c] + prev_U)
            G_psi_H[i*C + c] += current_U
            prev_U = current_U

    # --- STAGE 2: Apply Potential V^H ---
    psi_out_symm = np.zeros_like(psi_in)
    for j in prange(N):
        # The * unpacking works identically to the forward K matvec
        V_j = - construct_coupling_matrix_jit(grid[j], prefactor, C, *pot_data, radial_pot[j], *cent_data)
        
        # Complex conjugate transpose of V
        V_j_H = V_j.T.astype(np.complex128)
        
        # Multiply: V^H @ (G^H psi)
        psi_out_symm[j*C : (j+1)*C] = V_j_H @ G_psi_H[j*C : (j+1)*C]

    # --- STAGE 3: De-symmetrize (using the safe explicit loop!) ---
    psi_out = np.empty_like(psi_in)
    for i in prange(N):
        for k in range(C):
            psi_out[i*C + k] = psi_out_symm[i*C + k] * sqrt_w[i]
            
    return psi_out

@njit
def apply_K_P(psi_vec, eigvals, u_T, v_T):
    """
    Computes the action of the divergent part of the kernel, K_D, on a state vector (Eq. (16) in the manuscript).

    K_D|ψ⟩ = sum(eta_i * |u_i⟩ * ⟨v_i|ψ⟩) for all divergent eigenvalues.
    
    Parameters
    ----------
    psi_vec : np.ndarray
        The state vector |ψ⟩ to project.
    eigvals : np.ndarray
        The divergent Weinberg eigenvalues (eta).
    u_T : np.ndarray
        Transposed right-eigenvectors (the |u_i⟩ states).
    v_T : np.ndarray
        Transposed, biorthogonalized left-eigenvectors (the ⟨v_i| states).

    Returns
    -------
    np.ndarray
        The resulting regularized state vector correction.
    """
    res = np.zeros_like(psi_vec)
    psi_contig = np.ascontiguousarray(psi_vec)
    for i in range(len(eigvals)):
        coeff = np.vdot(v_T[i], psi_contig)
        res += eigvals[i] * u_T[i] * coeff
    return res